services:
  app:
    build: .
    container_name: mapan-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    network:
      - private-net

networks:
  private-net:
    external: true
